# Generated by Django 5.1.3 on 2025-03-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='is_correct',
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='student_answer',
            field=models.TextField(),
        ),
    ]
