# Generated by Django 5.1.3 on 2025-03-02 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_studentanswer_is_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentexamattempt'),
        ),
    ]
