# Generated by Django 5.1.3 on 2025-03-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentanswer_is_correct_alter_studentanswer_attempt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='full_name',
            new_name='student_name',
        ),
    ]
