# Generated by Django 5.1.3 on 2025-03-02 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_full_name_student_student_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_name',
            new_name='full_name',
        ),
    ]
