# Generated by Django 5.1.3 on 2025-03-03 00:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_exam_duration'),
        ('students', '0005_rename_student_name_student_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamattempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='studentexamattempt',
            unique_together={('student', 'exam')},
        ),
    ]
