# Generated by Django 5.1.3 on 2025-06-06 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_studentexamattempt_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='ai_confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='ai_detection_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='doctor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='manual_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='original_score',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='similarity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='ai_analysis_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='total_ai_detected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='total_flagged_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='students.studentexamattempt'),
        ),
        migrations.CreateModel(
            name='AIAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_timestamp', models.DateTimeField(auto_now_add=True)),
                ('ai_detection_raw', models.TextField()),
                ('similarity_raw', models.TextField()),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, max_length=100)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('student_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='students.studentanswer')),
            ],
        ),
    ]
