# Generated by Django 5.1.3 on 2024-11-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_rename_type_question_question_type_alter_exam_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='code',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
    ]
