# Generated by Django 5.1.3 on 2025-03-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_remove_question_correct_answer_examsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.IntegerField(default=30),
        ),
    ]
