# Generated by Django 5.1.3 on 2024-11-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_deadline_question_image_student_examresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolled_exams',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ExamResponse',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
