apiVersion: v1
kind: PersistentVolume
metadata:
  name: guarded-exam-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /home/ali/guarded-exam-data
  volumeMode: Filesystem

